<?php
/*
 * This file is part of the sonata project.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\ProductBundle\Entity;

use Application\ProductBundle\Entity\{{ product }}Repository;
use Application\ProductBundle\Product\{{ product }}\{{ product }}AddBasket;
use Application\ProductBundle\Product\{{ product }}\{{ product }}AddBasketForm;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   custom repository : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en#querying:custom-repositories
 *   query builder     : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/query-builder/en
 *   dql               : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/dql-doctrine-query-language/en
 *
 * @author <yourname> <youremail>
 */
class {{ product }}Repository extends \Sonata\Bundle\ProductBundle\Entity\BaseProductRepository
{

    /**
     * This function return the form used in the product view page
     *
     * @param  $product
     * @param  $validator
     * @param array $options
     * @return Application\ProductBundle\Products\{{ product }}\{{ product }}AddBasketForm
     */
    public function getAddBasketForm($product, $validator, $options = array())
    {
        // create the product form
        $product_basket = new {{ product }}AddBasket;
        $product_basket->setProduct($product);
        $product_basket->setQuantity(1);

        // create the form
        return new {{ product }}AddBasketForm('basket', $product_basket, $validator, $options);
    }
}